# Generated by Django 4.1.3 on 2022-12-12 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_proddetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proddetails',
            name='Name',
        ),
    ]
